services:
  backend:
    build:
      context: ./calendar-be
      dockerfile: Dockerfile
      args:
        PORT: ${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      PORT: ${BACKEND_PORT}
      USER_SECRET_KEY: ${USER_SECRET_KEY}
      USER_EXPIRES_IN: ${USER_EXPIRES_IN}
      MONGO_URL: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:${MONGO_PORT}/"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./calendar-fe
      dockerfile: Dockerfile
      args:
        PORT: ${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      PORT: ${FRONTEND_PORT}
      REACT_APP_BASE_URL: http://localhost:${BACKEND_PORT}
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
